version: '3'
services: 

  zookeeper: 
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: zookeeper
    ports:
      -"2181:2181"
    environment: 
    - ZOOKEEPER_CLIENT_PORT: 2181
    - ZOOKEEPER_TICK_TIME: 2000   #zookeeper heartbeats
    networks:
      - pgfd-network
  
  

