version: '3'

services:
  database_server:
    image: cloudsuite/web-serving:db_server
    container_name: database_server
    ports:
      - 3306:3306
  
  memcache_server:
    image: cloudsuite/web-serving:memcached_server
    container_name: memcache_server
    ports:
      - 11211:11211

  web_server:
    image: cloudsuite/web-serving:web_server
    container_name: web_server
    depends_on:
      - database_server
      - memcache_server
    ports:
      - 8080:80
